### PR TITLE
French teachers

### PR DESCRIPTION
**Pull request by mccurdy42**
Hello
0) there are merge conflicts and I am trying to resolve them. 
1) replace the feb_6 xlsx with a smaller sheet and have french in any order
2) use the testing txt for easier checks that the number of french classes match

### CODE REVIEW

**Comment by ajacobs12** [comment]
I have not run this locally yet, but I did notice one thing while reviewing the code. At line 299 you have the rows being incremented by 2 as we are dealing with merged cells, but in the new excel sheet this is no longer the case. Because of the last front end iteration, we have the cell values copying over, the rows are no longer merged, so we do not need to increment by 2. I would try running your code with the new formatted excel sheets to make sure it still works properly!

**Comment by mccurdy42** [comment]
There were a few frustrations on how the files were merged with some changes being ported over from master and overwriting local files. Conversely, local changes were added when they were from master. I have gone through it line by line to verify what had been changed and what had not. please let me know if there are other irregularities from it. thanks

**Comment by mccurdy42** [comment]
One may test on this file 
[french_teacher_testing_feb28.xlsx](https://github.com/team13-fydp/fydp/files/4269380/french_teacher_testing_feb28.xlsx)

**Review by mestrona3 — APPROVED** [review]
Tested the code on smaller subset, french_teacher_testing_feb28.
French teachers are re-arranged so they are at the end of the teacher matrix. I tried a couple different combos and worked every time. # of french teacher is captured properly, fte is re-ordered based on french teachers moving around, all looks good!

**Pull request merged**
