### PR TITLE
Initial Java Model Conversion

### PR DESCRIPTION
**Pull request by ajacobs12**
First iteration of the Java model conversion from OPL based on the **current** master branch from the 4fydp repository.

Instructions: 
1. Open and run the current master branch of 4fydp to get the baseline objective value from OPL to use as comparison in Java
2. Open and run allison_javaModel on local computer and ensure there are no array out of bound errors and that CPLEX is properly called and can run with no infeasibility concerns
3. Lines 743 to the end contain code to check that the minute constraints are being withheld for each of the cohorts. To test this specifically you should do the following tests:

- Change the Cohort (k) in the if statements on lines 758-777 to represent a Primary Cohort (k=0,1,2)
**Test:** Ensure that they are receiving 500 minutes of Language and NO French while meeting the other constraints 
-  Change the Cohort (k) in the if statements on lines 758-777 to represent a Junior/ Intermediate Cohort (k=3,4,5,6,7,8,9,10)
**Test:** Ensure they are receiving only 300 minutes (min) of language and 200 minutes (min) of French while meeting  the other minute constraints

4. The initial code runs include a display of all teachers, cohorts, subjects and periods similar to OPL. This can be exported to Excel and a few other conditions can be checked:

- Cohort 11 and 12 should only ever be scheduled subjects "Away" and "Prep" respectively

- Each Cohort should be scheduled for exactly 30 periods for the entire week

- Teacher 15 and 16 should be scheduled for only French, Away or Prep (there are two anomalies with Teacher 4 teaching French, this was addressed in a later OPL model, but not off the current version of master)

### CODE REVIEW

**Review by ahopkins19 — COMMENTED** [review]
All of the tests passed, and I checked minute reqs for different cohorts. Objective values match. I also went through the lines of code for formatting- the only thing I would suggest is to give more info in the comments for some of the constraints (specifically the assignment ones). I think there is a little bit of an explanation in the OPL version so could probably just copy those over.

**Review by mestrona3 — COMMENTED** [review]
Objective values between CPLEX and Java matched, with run time of 3.7 minutes. Ran the tests to check subject/cohort/minute constraints and they were all satisfied! 

One minor change (more of a nice to have not an actual error) is I know we are outputting cohorts starting at 0, what do we think about showing 'time' starting at 1 instead of 0? i.e. going from 1-30? Would be easier to read. We may have made this fix in a later version of the model?

**Comment by ahopkins19** [comment]
Could you also print out the day?

**Comment by ajacobs12** [comment]
Changes made based on comments from @ahopkins19 and @mestrona3! Great feedback, thanks team!

**Review by ahopkins19 — APPROVED** [review]

**Pull request merged**
